const CMD_SYNC* = "sync"
const CMD_START* = "start"
const CMD_BUILD* = "build"
const CMD_TEST* = "test"
const CMD_SUBMIT* = "submit"
const CMD_NEXT* = "next"
const CMD_SELECT* = "select"

const OPT_BROWSER* = "browser"
const OPT_PROFILE* = "profile"
const OPT_FORCE* = "force"
