name: build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nim
      run: |
        brew install nim

    - name: Install Zig
      run: |
        brew install zig

    - name: Install Docker
      run: |
        curl -OSL https://raw.githubusercontent.com/Homebrew/homebrew-core/dc0669eca9479e9eeb495397ba3a7480aaa45c2e/Formula/qemu.rb brew install ./qemu.rb
        brew link --overwrite qemu
        colima start

    - name: Build
      run: |
        ./build.sh
