name: build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nim
      run: |
        brew install nim

    - name: Install Zig
      run: |
        brew install zig

    - name: Build
      run: |
        nimble install -y
        ./build.sh

    - name: Upload nlcc
      uses: actions/upload-artifact@v4
      with:
        name: nlcc
        path: build/mac/nlcc

    - name: Upload nlcc.exe
      uses: actions/upload-artifact@v4
      with:
        name: nlcc.exe
        path: build/win/nlcc.exe

    - name: Zip dlls.zip
      run: zip -jrq build/dlls.zip build/dlls

    - name: Upload dlls.zip
      uses: actions/upload-artifact@v4
      with:
        name: dlls.zip
        path: build/dlls.zip

    - name: Zip tmpl.zip
      run: cd build && zip -rq ../tmpl.zip tmpl

    - name: Upload tmpl.zip
      uses: actions/upload-artifact@v4
      with:
        name: tmpl.zip
        path: build/tmpl.zip
